import { AlertCircle } from 'lucide-react';

export function Disclaimer({ variant = 'inline' }: { variant?: 'inline' | 'banner' }) {
  if (variant === 'banner') {
    return (
      <div className="flex items-start gap-3 rounded-xl bg-warning-50 p-4 ring-1 ring-warning-200">
        <AlertCircle className="mt-0.5 h-5 w-5 shrink-0 text-warning-600" />
        <p className="text-sm leading-relaxed text-warning-800">
          <span className="font-600">Educational use only.</span> This prediction is generated by a
          machine-learning model for research and educational purposes. It is{' '}
          <span className="font-600">not a medical diagnosis</span> and should not replace professional
          medical advice. Always consult a qualified healthcare provider.
        </p>
      </div>
    );
  }
  return (
    <p className="flex items-start gap-2 text-xs leading-relaxed text-ink-500">
      <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-ink-400" />
      <span>
        Predictions are for educational and research purposes only and are not a substitute for
        professional medical diagnosis.
      </span>
    </p>
  );
}
