import { Activity, AlertCircle } from 'lucide-react';
import type { Page } from './Navbar';

interface FooterProps {
  onNavigate: (page: Page) => void;
}

export function Footer({ onNavigate }: FooterProps) {
  return (
    <footer className="mt-24 border-t border-ink-200 bg-ink-900 text-ink-300">
      <div className="container-page py-12">
        <div className="grid gap-8 md:grid-cols-3">
          <div>
            <div className="flex items-center gap-2">
              <span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-primary-500 to-accent-500 text-white">
                <Activity className="h-5 w-5" strokeWidth={2.5} />
              </span>
              <span className="font-display text-lg font-700 text-white">
                Health<span className="text-primary-400">Predict</span>
              </span>
            </div>
            <p className="mt-3 max-w-xs text-sm leading-relaxed text-ink-400">
              Multiple Disease Prediction Using Machine Learning — an educational and research-focused
              healthcare prediction platform.
            </p>
          </div>

          <div>
            <h4 className="text-sm font-600 uppercase tracking-wider text-ink-400">Navigate</h4>
            <ul className="mt-3 space-y-2 text-sm">
              {[
                { id: 'home' as Page, label: 'Home' },
                { id: 'predictions' as Page, label: 'Predictions' },
                { id: 'about' as Page, label: 'About' },
                { id: 'contact' as Page, label: 'Contact' },
              ].map((l) => (
                <li key={l.id}>
                  <button onClick={() => onNavigate(l.id)} className="text-ink-300 transition hover:text-primary-400">
                    {l.label}
                  </button>
                </li>
              ))}
            </ul>
          </div>

          <div className="rounded-xl bg-ink-800 p-4 ring-1 ring-ink-700">
            <div className="flex items-start gap-2">
              <AlertCircle className="mt-0.5 h-5 w-5 shrink-0 text-warning-400" />
              <p className="text-xs leading-relaxed text-ink-400">
                <span className="font-600 text-ink-200">Disclaimer:</span> HealthPredict is an
                educational and research tool. Predictions are generated by machine-learning models and
                are <span className="text-ink-200">not a medical diagnosis</span>. Always consult a
                qualified healthcare professional.
              </p>
            </div>
          </div>
        </div>

        <div className="mt-10 flex flex-col items-center justify-between gap-3 border-t border-ink-800 pt-6 text-xs text-ink-500 sm:flex-row">
          <p>© {new Date().getFullYear()} HealthPredict. For educational and research purposes only.</p>
          <p>Built with React, Vite &amp; Tailwind CSS</p>
        </div>
      </div>
    </footer>
  );
}
